### ISSUE TITLE
Proper example 

### ISSUE THREAD

**Issue by Yogesh-333** [ConnectyCube/connectycube-flutter-call-kit#10]
can you please provide a proper example

**Comment by TatankaConCube** [comment]
you can use [this app](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample) as an example

**Comment by Yogesh-333** [comment]
i want only the call notification part . Any help with that?

**Comment by Yogesh-333** [comment]
Any idea ?

**Comment by TatankaConCube** [comment]
for only showing call notification use this [part of the code](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/66eb89d787baeef1c5589c4e0e1dc3be8a70824a/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L172)

**Comment by TatankaConCube** [comment]
we prepared detailed documentation for version [2.0.0](https://pub.dev/packages/connectycube_flutter_call_kit/versions/2.0.0), use it
