### ISSUE TITLE
Background voip push doesnt receive

### ISSUE THREAD

**Issue by senkia24** [ConnectyCube/connectycube-flutter-call-kit#102]
Sometimes my app doesnt receive voip push background or killed state. 
IOS 16.5 Iphone se

**Comment by TatankaConCube** [comment]
just for clarification, don't you receive VoIP notifications or the CallKit doesn't show? You can check it in the log. If your app starts in the background after receiving the VoIP notification but the CallKit doesn't show, try to init this plugin as earlier as possible by calling `ConnectycubeFlutterCallKit.instance.init();`. You can do it in the `initState()` of your App widget. Then you can call this method again with the required configurations in any place of your app as you did before. This issue reproduces only on iOS 16.5 and doesn't reproduce on older versions, but we haven't found any changes related to this issue in the release notes for iOS 16.5.

Do you use the Connectycube platform for working with VoIP notifications? If so, please follow [these](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/95#issuecomment-1567957374) notes about the VoIP notifications.

**Comment by senkia24** [comment]
Voip push doesn't receive
I logged

**Comment by TatankaConCube** [comment]
> Do you use the Connectycube platform for working with VoIP notifications?

?
