### ISSUE TITLE
Accept call automatically 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [ConnectyCube/connectycube-flutter-call-kit#104]
Is it possible to accept call automatically without using the UI and even disconnect call after sometime automatically without using the UI?
(any android event to accept incoming calls in latest Android telecom package?)

**Comment by TatankaConCube** [comment]
sorry for the delay with answer. starting the version  2.6.0 you have the callback `onCallIncoming` which fires before display the Call notification. you can try to use it for automatic accepting the call immediately after receiving the push notification
