### ISSUE TITLE
[iOS] calls not listed in the CallKit recent history

### ISSUE THREAD

**Issue by berger89** [ConnectyCube/connectycube-flutter-call-kit#105]
We need the possibility to add accepted and rejected calls to the CallKit Recent History.
Is this possible with the connectycube-flutter-call-kit?

**Comment by TatankaConCube** [comment]
sorry, but we don't support it in the current version. you can enable it by yourself by changing [this parameter](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/ios/Classes/CallKitController.swift#L67) to `true`. But it just will add the calls to the calls history and you should develop by yourself the launching the app by clicking on the call from your app in the recent list.

**Comment by berger89** [comment]
@TatankaConCube 
Thank you, that helps us already!
But one more question:
Incoming calls that were accepted/rejected via the notification are displayed in the callkit history (if we set the `includesCallsInRecents` to `true`). But which method do we have to trigger if we want to show outgoing calls as well in the history?

**Comment by TatankaConCube** [comment]
we haven't implemented it, you can see at the method [`startCall`](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/ios/Classes/CallKitController.swift#L262) and develop API for calling it from the Dart side. Additionally, you can see the code of the [flutter_callkit_incoming](https://pub.dev/packages/flutter_callkit_incoming) plugin. It is also written in the Swift language and you can see how they do it in their plugin.
