### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-call-kit#106]
FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:checkDebugAarMetadata'.

    Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
    Failed to transform android-104.5112.07.aar (com.github.webrtc-sdk:android:104.5112.07) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
    > Could not find android-104.5112.07.aar (com.github.webrtc-sdk:android:104.5112.07).
    Searched in the following locations:
    https://jitpack.io/com/github/webrtc-sdk/android/104.5112.07/android-104.5112.07.aar
    https://jitpack.io/com/github/webrtc-sdk/android/104.5112.07/android-104.5112.07.jar

,Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on Ubuntu 22.04.2 LTS 5.19.0-43-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (3 available)
[✓] Network resources

**Comment by TatankaConCube** [comment]
What version of Connectycube SDK do you use? Or if you don't use it, what version of the flutter_webrtc lib do you use?

**Comment by prashantjdgit** [comment]
connectycube_sdk: ^2.3.0
connectycube_flutter_call_kit: ^2.2.2

 we are using the connectycube sdk , not integrating the webrtc directly

**Comment by TatankaConCube** [comment]
Please try the latest versions of these libs
