### ISSUE TITLE
Call notification closes with no event if you do not hit the either Accept or Decline

### ISSUE THREAD

**Issue by beebobox** [ConnectyCube/connectycube-flutter-call-kit#110]
Hi 
Thanx for a great module :)

The below issue is for android.
Is is possible to prevent dismiss of the notification if you accidentially hit the area outside of the buttons?

if not possible to prevent dismiss, could the fullscreen Accept/Reject screen be shown if the user dismisses the notification by touching the area surrounding the buttons?

..Or have an event that fires if this happens, so that I can detect that the app needs to display Accept/Reject?
This will help a great deal in making a cleaner design, and ensuring that the output from displaying a Call notification is allways a detectable Accept, Reject (or Dismissed if an event for this is added.)

Keep up the great work :)

br. Jacob

**Comment by TatankaConCube** [comment]
sorry for the delay with the answer. after the clicking on the notification the app should be launched. then you can get the state of the latest call and if it is "pending" you can show the Incoming call screen inside your Flutter app.
