### ISSUE TITLE
How to open app in terminated state on answer call button

### ISSUE THREAD

**Issue by ArbabShujaat** [ConnectyCube/connectycube-flutter-call-kit#119]
connectycube_flutter_call_kit working in background  but when in terminated state and click on accept button i am unable to open the app

**Comment by TatankaConCube** [comment]
please search for similar issues before creating a new one, there is the solution for your problem https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/111

**Comment by ArbabShujaat** [comment]
thank you after adding the permission, Now i can open the app
