### ISSUE TITLE
Possible to open the app upon tapping the "Decline" action?

### ISSUE THREAD

**Issue by danny-low** [ConnectyCube/connectycube-flutter-call-kit#123]
Hello,

I am exploring if there's a configuration option to launch the app when a call is declined. In my app, users automatically log out after a set time (x period), so when users decline a call after they have been logged out, I want to redirect them to the login page before any further action. Presently, tapping the notification or accepting the call successfully opens the app, which is working perfectly, but I'm seeking a way for the decline action to do the same.

**Comment by TatankaConCube** [comment]
In most cases, the Reject button doesn't involve opening the app. We have not added this functionality. You have the `onCallRejected` and the `onCallRejectedWhenTerminated` callbacks and you can try to use them for your needs.
