### ISSUE TITLE
onCallAccepted in background mode

### ISSUE THREAD

**Issue by ilhamchp** [ConnectyCube/connectycube-flutter-call-kit#13]
Hi, I've use this library and it's very helpful. It's work on background (app killed), but it doesn't work on background (app minimized). So here's my logic :

1. FCM trigger App to show incoming call
2. Users answer it, and app saved "call data" from FCM using shared preferences
3. App opened and connect to the caller using "call data" from shared preferences
4. Call connected

And my Code 
<img width="686" alt="Screen Shot 2021-06-08 at 11 44 05" src="https://user-images.githubusercontent.com/34804048/121124342-f5b1b300-c84e-11eb-8627-e3dd47c3c890.png">

However, when the app is minimized, the step 3 is not executed, it won't connect to the caller, because the call data is missing. So I'm guessing the onCallAccepted is not executed when the app is in background mode (app minimized). Any solution for this case?

Thanks

**Comment by TatankaConCube** [comment]
Hmmm... it is interesting, it should work. Do you init `connectycube-flutter-call-kit` when the app started or only before showing the notification? Please take a look at our sample [p2p_call_sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample) where your case works well.

**Comment by ilhamchp** [comment]
I'm sorry, after I did some research, this library actually works perfect, but the SharedPreferences cause this issue. Because the onBackgroundMessage run isolated, so I should do prefs.reload(); before getString from SharedPreferences, if I didn't call that, the return would be missing. So, I'm closing this issue, thanks.
