### ISSUE TITLE
Error: ConnectycubeFlutterBgPerformingService

### ISSUE THREAD

**Issue by kostricanitechnology** [ConnectyCube/connectycube-flutter-call-kit#131]
IM getting the following error when I try to build the app after updating the plugin. I am using Flutter version 3.16.7

e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFlutterCallKitPlugin.kt:20:83 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFlutterCallKitPlugin.kt:133:17 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFlutterCallKitPlugin.kt:401:9 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/EventReceiver.kt:11:83 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/EventReceiver.kt:56:21 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/EventReceiver.kt:94:21 Unresolved reference: ConnectycubeFlutterBgPerformingService
e: file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/connectycube_flutter_call_kit-2.6.0/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/background_isolates/FlutterConnectycubeBackgroundExecutor.kt:49:9 Unresolved reference: ConnectycubeFlutterBgPerformingService

**Comment by kostricanitechnology** [comment]
It is fixed by deleting the cache manually and deleting the build folder and dart.tool folder

**Comment by TatankaConCube** [comment]
please close the ticket if your issue was resolved
