### ISSUE TITLE
How to launch app 

### ISSUE THREAD

**Issue by MuhammadNauman123456** [ConnectyCube/connectycube-flutter-call-kit#134]

**Comment by MuhammadNauman123456** [comment]
I want to luanch my app from terminated state when user accept call in ios

**Comment by TatankaConCube** [comment]
it is the limitation of the iOS system, it will open the CallKit for audio call or ask to unlock the device for opening your app for the video call. what type of calls do you mean?

**Comment by hatemragab** [comment]
great 
what about the android
