### ISSUE TITLE
Accept button on incoming call not working in terminated state (Android / Flutter)

### ISSUE THREAD

**Issue by prashantJangidSys** [ConnectyCube/connectycube-flutter-call-kit#142]
Flutter version -Channel stable, 3.16.5
Connectycube callkit version - 2.7.0

I'm facing the issue when I accept the incoming call in terminated state . 
The methods which are specified in the library documentation is not implemented in the code sample also.
-E/FlutterConnectycubeBackgroundExecutor(18896): action_call_incoming background handler has not been registered.
E/FlutterConnectycubeBackgroundExecutor(18896): action_call_accept background handler has not been registered.

This issue is not raised in older versions of the library , but not working as required in latest update.
Feel free to provide a solution or suggestions if you have any! Your input is greatly appreciated. Thank you!

**Comment by TatankaConCube** [comment]
these logs just mean that the callbacks `onCallAcceptedWhenTerminated` and `onCallIncomingWhenTerminated`
 were not implemented in your app. these logs were reworked in this pull [request]( https://github.com/ConnectyCube/connectycube-flutter-call-kit/pull/129)

> The methods which are specified in the library documentation is not implemented in the code sample also.

there are specific callbacks and we don't need them in our sample


> This issue is not raised in older versions of the library 

you can use older version if you don't require new functionality. also you can be free do investigate the issue in the newest versions and do pull request with fixes. as you can see it is an open-source project and every developer can propose any fixes or features

**Comment by prashantJangidSys** [comment]
Thank you for your support
