### ISSUE TITLE
incoming call notification is not appearing when a call is triggered.

### ISSUE THREAD

**Issue by muj-i** [ConnectyCube/connectycube-flutter-call-kit#146]
Just showing this log in the console, but the CallKit incoming call notification is not coming.

![log](https://github.com/ConnectyCube/connectycube-flutter-call-kit/assets/99077742/7d10f401-eb46-44bc-8a71-323f2ba8c655)

**Comment by TatankaConCube** [comment]
Please, check the data types first. Here are the expected types on the iOS side but Android expects the same:
```dart
let callId = callData["session_id"] as! String
let signalingType = callData["signal_type"] as? String
let callType = callData["call_type"] as! Int
let callInitiatorId = callData["caller_id"] as! Int
let callInitiatorName = callData["caller_name"] as! String
let callOpponentsString = callData["call_opponents"] as! String
let callOpponents = callOpponentsString.components(separatedBy: ",").map { Int($0) ?? 0 }
let userInfo = callData["user_info"] as? String
```
Also, pay attention to the `session_id` should be the valid `UUID` string.

**Comment by muj-i** [comment]
ok go it.
now there is a another issue that is.
if i tap on the incoming calling notification.it should show the full screen incoming calling ui right?
but it just dismissing the notification.
any solution for that?

**Comment by TatankaConCube** [comment]
> it should show the full screen incoming calling ui right?

no, the app should launch or move to the foreground on Android and the fullscreen should open on the iOS

**Comment by muj-i** [comment]
when the android app is in the terminated state it is unable to trigger the callkit notification incoming call.
and it logs this

![log](https://github.com/ConnectyCube/connectycube-flutter-call-kit/assets/99077742/87138dda-14cd-42b6-80c3-e07b9cd86ab3)
