### ISSUE TITLE
Incoming Callkit notification not triggering when app is terminated 

### ISSUE THREAD

**Issue by muj-i** [ConnectyCube/connectycube-flutter-call-kit#147]
this is the error log when app is terminated and a call notification arrived from FCM. It didn't trigger the callkit incoming call notification rather logging this

![log](https://private-user-images.githubusercontent.com/99077742/325625755-87138dda-14cd-42b6-80c3-e07b9cd86ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTAxNjUsIm5iZiI6MTcxNDEwOTg2NSwicGF0aCI6Ii85OTA3Nzc0Mi8zMjU2MjU3NTUtODcxMzhkZGEtMTRjZC00MmI2LTgwYzMtZTA3YjljZDg2YWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzOTIyNWViNTI1Mzc2NzcwYjkzYjc1YTg2NjZlOGRhMjIzOWFkZmI2ZDlhNDlhYzNmYzEwZjliYzAxNjc2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkHleAG4Hxgy-87OLMTJ-3YKfhEBimnDj-feK3RI9tk)

**Comment by TatankaConCube** [comment]
the image can't be loaded((( 
please share logs and code in text format only

**Comment by muj-i** [comment]
```
I/flutter (21552): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (21552): PlatformException(java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly., Exception, Cause: null, Stacktrace: java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly.
I/flutter (21552):      at io.flutter.plugins.firebase.core.i.v(Unknown Source:12)
I/flutter (21552):      at io.flutter.plugins.firebase.core.i.l(Unknown Source:0)
I/flutter (21552):      at io.flutter.plugins.firebase.core.b.run(Unknown Source:4)
I/flutter (21552):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
I/flutter (21552):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
I/flutter (21552):      at java.lang.Thread.run(Thread.java:1012)
I/flutter (21552): , null)
```

**Comment by TatankaConCube** [comment]
sorry, but I can't see any plugin code in the stacktrace. could you please add more details about this issue? have you configured correctly your app for the plugin integration?

**Comment by muj-i** [comment]
This is my FCM background handler
This works absolutely fine when the app is in the background but not terminated, but it can't trigger the CallKit when the app is terminated.
```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
   await Firebase.initializeApp();
  

  String docName = '';
  String docImage = '';
  Uuid uuid = const Uuid();

  if (message.data['type'] == 'call') {
  docName = message.data['doc_name'];
  docImage = message.data['doc_image'];

  var callerId = Random().nextInt(999999);
  var opponentsIds = {Random().nextInt(999999)};
    CallEvent callEvent = CallEvent(
      sessionId: uuid.v4(),
      callType: 0,
      callerId: callerId,
      callerName: docName,
      opponentsIds: {opponentsIds},
      callPhoto: 'docImage',
    );
    ConnectycubeFlutterCallKit.showCallNotification(callEvent);
  } 
  dev.log("Handling a background message: ${message.messageId}");
}
```
