### ISSUE TITLE
iOS accepting call from lockscreen opens default call screen instead of app

### ISSUE THREAD

**Issue by coreyfreeman82** [ConnectyCube/connectycube-flutter-call-kit#150]
When I accept an incoming call and have my app running in the background but my phone is locked, it shows the default call screen on iOS instead of asking to unlock my phone and go to my app. If I click on the app button on the call screen it does navigate correctly. I placed some logs in the accepted event which I can all see so the code is being executed it just doesn't navigate to my app directly

**Comment by TatankaConCube** [comment]
It is the expected behavior of the iOS system CallKit feature for audio calls. For video calls, it should ask you to unlock your phone and navigate to your app.
