### ISSUE TITLE
Ringtone sound not working

### ISSUE THREAD

**Issue by shatanikmahanty** [ConnectyCube/connectycube-flutter-call-kit#22]
**Platform (use [x])**
- [x] Android
- [ ] iOS

**Describe the bug:**

Notification sound is not working for p2p calls

**Additional info**

I am getting incoming call notifications but the ringtone is not working

I think adding this code into the notification_manager.kt file in createCallNotification function will fix the problem but I am open to suggestion to fix the problem in case it is something wrong that I am writing in code.

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                mChannel = new NotificationChannel(CHANNEL_ID, Utils.CHANNEL_NAME, NotificationManager.IMPORTANCE_HIGH);
                mChannel.setLightColor(Color.GRAY);
                mChannel.enableLights(true);
                mChannel.setDescription(Utils.CHANNEL_SIREN_DESCRIPTION);
                AudioAttributes audioAttributes = new AudioAttributes.Builder()
                        .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                        .setUsage(AudioAttributes.USAGE_NOTIFICATION)
                        .build();
                mChannel.setSound(soundUri, audioAttributes);

                if (mNotificationManager != null) {
                    mNotificationManager.createNotificationChannel( mChannel );
                }
        }
```

**Comment by TatankaConCube** [comment]
The plugin takes it from the system and uses your system ringtone as a sound for the call notification. Do you have a default ringtone in your system? Do you use an emulator or a real device?

**Comment by TatankaConCube** [comment]
@shatanikmahanty I reviewed your code one more time and didn't found the differences between your code and [code in this plugin](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/NotificationsManager.kt#L269) except this line `.setUsage(AudioAttributes.USAGE_NOTIFICATION)`. Are you sure that `AudioAttributes.USAGE_NOTIFICATION` is right here? According to the documentation, the type `AudioAttributes.USAGE_NOTIFICATION_RINGTONE` is more suitable here.

**Comment by shatanikmahanty** [comment]
Thanks for reviewing I will update the code to your suggestion and check if it works

**Comment by TatankaConCube** [comment]
This is already implemented in our plugin, what do you want to check?

**Comment by shatanikmahanty** [comment]
I thought you wanted me to change parts of the code and check

**Comment by TatankaConCube** [comment]
No, I just said that it is already implemented in the plugin and I think it will not give result, need to search other reasons for this issue.

**Comment by shatanikmahanty** [comment]
Ooh ok got you now

**Comment by TatankaConCube** [comment]
could you please reply on my question https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/22#issuecomment-913461533

**Comment by shatanikmahanty** [comment]
Yes I have a default ringtone for the system and I tested my code on two real devices, one was android 11 and other was android 7

**Comment by jaween** [comment]
I noticed this same error on an Android 12 device. After running the `ConnectycubeFlutterCallKit.showCallNotification()` method, this error was reported:

```ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ERROR, UID 10370 does not have permission to content://media/external/audio/media/135?title=Coconut%20Mall%20(short)&canonical=1 [user 0], , null)```

On an Android 8 device, the same method worked fine and played the device's ringtone.

**Comment by shatanikmahanty** [comment]
> I noticed this same error on an Android 12 device. After running the `ConnectycubeFlutterCallKit.showCallNotification()` method, this error was reported:
> 
> `ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ERROR, UID 10370 does not have permission to content://media/external/audio/media/135?title=Coconut%20Mall%20(short)&canonical=1 [user 0], , null)`
> 
> On an Android 8 device, the same method worked fine and played the device's ringtone.

Yes for me it was only happening on android 11, couldno't test on android 12 due to lack of device

**Comment by MrunalrajRedij** [comment]
Hi, why is this issue closed. Has anyone found the sloution? I am facing similar issue.

**Comment by dkdanish98** [comment]
> > I noticed this same error on an Android 12 device. After running the `ConnectycubeFlutterCallKit.showCallNotification()` method, this error was reported:
> > `ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ERROR, UID 10370 does not have permission to content://media/external/audio/media/135?title=Coconut%20Mall%20(short)&canonical=1 [user 0], , null)`
> > On an Android 8 device, the same method worked fine and played the device's ringtone.
> 
> Yes for me it was only happening on android 11, couldn't test on android 12 due to lack of device

Has anyone find the solution for this?
