### ISSUE TITLE
connectycube_flutter_call_kit When will it support iOS? please

### ISSUE THREAD

**Issue by Basemshawwa** [ConnectyCube/connectycube-flutter-call-kit#33]
connectycube_flutter_call_kit When will it support iOS? please

**Comment by TatankaConCube** [comment]
duplicate of https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/3 
just FYI we have a work branch [feature/add_ios_support](https://github.com/ConnectyCube/connectycube-flutter-call-kit/tree/feature/add_ios_support) but it is unstable and has some differences between iOS and Android API and we still work on this feature.
