### ISSUE TITLE
Not getting chat notifications for android & ios devices

### ISSUE THREAD

**Issue by geetakher** [ConnectyCube/connectycube-flutter-call-kit#37]
**Please find below log when i get receive message:**

[log] ---Xmpp Receiving:---
I/flutter ( 1930): CB-SDK: : Receive PRIVATE chat message 61f29fc68510a35d15d7d7f4
[log] <message xmlns="jabber:client" to="5352743-5858@chat.connectycube.com" id="61f29fc68510a35d15d7d7f4" type="chat" from="5365103-5858@chat.connectycube.com/flutter_373524EA-F150-46F6-8FF6-6178F12B6A0B"><body>htjfgg</body><extraParams xmlns="jabber:client"><date_sent>1643290566</date_sent><save_to_history>1</save_to_history><dialog_id>61f28114276f93005bbd562e</dialog_id><message_id>61f29fc68510a35d15d7d7f4</message_id></extraParams><markable xmlns="urn:xmpp:chat-markers:0"/></message><r xmlns='urn:xmpp:sm:3' />

**Comment by TatankaConCube** [comment]
looks like your issue is not related to this repo, [there](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/73) is a similar issue
