### ISSUE TITLE
Not able to login new user getting 404

### ISSUE THREAD

**Issue by geetakher** [ConnectyCube/connectycube-flutter-call-kit#38]
REQUEST
flutter:   POST https://api.connectycube.com/session
flutter: HEADERS
flutter:   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 2.0.9, CB-Token: B3D6E33FDB4D2B26B7C03A1F3E3DA42638B3}
flutter: BODY
flutter:   {"application_id":"5858","auth_key":"yr-LkMB82ksb9CF","nonce":"143070309","timestamp":"1643293607","signature":"3857d0f0f8cb691f6a9849b40fb52ef3b1e544b5","user":{"login":"870d493648a6440a8b8d0b986b272262","email":"geeta9@yopmail.com","password":"123456"}}
flutter:
flutter: CB-SDK: : *********************************************************
flutter: *** RESPONSE *** 404 *** aa6e3e57-cce3-4593-9644-54a83f5fc05a ***
flutter: HEADERS
flutter:   {connection: keep-alive, content-type: application/json; charset=utf-8, date: Thu, 27 Jan 2022 14:26:48 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 29, server: nginx/1.16.1}
flutter: BODY
flutter:   {"errors":["User not found"]}
flutter:
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: type 'ResponseException' is not a subtype of type 'String'
flutter:

**Comment by TatankaConCube** [comment]
the issue is not related to the current repo, please create your answer in the right repo
