### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by jenniestrongbow** [ConnectyCube/connectycube-flutter-call-kit#4]
Can you pls show us a basic example of how to display a notification over the lock screen?

Thanks

**Comment by TatankaConCube** [comment]
You can see an example in our [P2P Calls sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample). This [part](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L172) shows the call screen.
