### ISSUE TITLE
Push notification from killed state

### ISSUE THREAD

**Issue by Space-Meet** [ConnectyCube/connectycube-flutter-call-kit#41]
Hi, I would like to know if it possible to use the call kit to show incoming call screen using firebase push notification, I can see that there is already a guide showing how to do that using ConnectyCubeSDK in this link: https://github.com/ConnectyCube/connectycube-flutter-call-kit#show-incoming-call-screen-by-push-notification.

But I would like to do it without the ConnectyCubeSDK. What I want to do is the following:

2 Users (User X and User Y)

User X calls User Y (Currently app is in killed state), User Y gets an incoming call screen and when the user accepts I want to run a certain logic in the app, I already have an audio/call system implemented so that part is already covered. It's just the ringing part that is left

**Comment by TatankaConCube** [comment]
you can use any service for push notifications but the `data` of the push notification should contain all these parameters

**Comment by Space-Meet** [comment]
@TatankaConCube I am sending the following data as a push notification, I am receiving the push notification but there is no ringing or any indication that the user is receiving a call. This is the data I am sending:


`{
  parameters: '{"message":"Incoming Audio call","call_type":"2","caller_id":"6125f56bdcd3aa28a5eb5f5f","caller_name":"mohamed-test","call_opponents":"614058ad5badd23ed3620418","ios_voip":"1"}',
  notificationType: 'push',
  environment: 'development',
  eventType: 'null',
  usersIds: '614058ad5badd23ed3620418',
  externalUsersIds: '[]',
  usersTagsAll: '[]',
  usersTagsAny: '[]',
  usersTagsExclude: '[]',
  date: 'null',
  endDate: 'null',
  period: 'null',
  name: 'null'
}`


And this is how I am sending the push notification from the backend (NodeJS):

`var message = {
      notification: {
        title,
        body,
      },
      data: data != null ? data : {},
      topic,
    };
    admin
      .messaging()
      .send(message)
      .then((response) => {
        // Response is a message ID string.
        console.log("Successfully sent message:", response);
      })
      .catch((error) => {
        console.log("Error sending message:", error);
      });`

**Comment by TatankaConCube** [comment]
do you send `parameters` as `data` for push notification? if you see the [code for parsing](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/android/src/main/kotlin/com/connectycube/flutter/connectycube_flutter_call_kit/ConnectycubeFCMService.kt#L43) `data` from the push notification you don't send the required parameter `session_id ` and some parameters you send with wrong types:

`caller_id` should be an integer
`call_opponents` should by the string with integers separated by ','

**Comment by Space-Meet** [comment]
Hi @TatankaConCube, so I checked the link for code parsing and it helped understanding how things are handled.

I have checked the types you were talking about but I am still not getting the call notification automatically, the data in the notification is looking this now:
`{
  message: 'Incoming Audio call',
  signal_type: 'startCall',
  call_type: '2',
  session_id: '801017f7-b1d5-4bc7-9329-00bdb5d4af94',
  caller_id: '617',
  caller_name: 'mohamed-test',
  call_opponents: '517',
  ios_voip: '1',
  notificationType: 'push',
  environment: 'development',
  eventType: 'null',
  usersIds: '517',
  externalUsersIds: '[]',
  usersTagsAll: '[]',
  usersTagsAny: '[]',
  usersTagsExclude: '[]',
  date: 'null',
  endDate: 'null',
  period: 'null',
  name: 'null',
  caller: '6125f56bdcd3aa28a5eb5f5f',
  callee: '614058ad5badd23ed3620418'
}`


I am using the device's token that I got from `ConnectycubeFlutterCallKit.getToken()` to send/receive notifications, but I am still not receiving a call notification, is there anything wrong with the payload I am sending ?

**Comment by TatankaConCube** [comment]
do you send it as VoIP or as the common APNS push? You should send it as the VoIP push notification

**Comment by Space-Meet** [comment]
I am currently working on just Android to Android, I will come to the iOS part later on. 

Correct me if I am wrong but in Android there isn't such thing as a voip notification, the closest thing to that is just sending a notification to the device with high priority no ?

**Comment by Space-Meet** [comment]
Also I can send a push notification and then manually check if it has the parameters signal_type so on and so forth, this is how it was done in the p2p_call_sample repo from Connectycube samples, but if I do that then it defeats the whole purpose of the CallKit automatically showing the call correct ?

**Comment by TatankaConCube** [comment]
> Correct me if I am wrong but in Android there isn't such thing as a voip notification, the closest thing to that is just sending a notification to the device with high priority no ?

you are right, for Android you should send common FCM push notification

> if I do that then it defeats the whole purpose of the CallKit automatically showing the call correct ?

choose any convenient tools suitable for your project, you can show Incoming call screen manually from your app, here no any problems
