### ISSUE TITLE
How to send the user_info data via VoIP push

### ISSUE THREAD

**Issue by GrupoDO** [ConnectyCube/connectycube-flutter-call-kit#42]
Hello!

I'm sending the user_info as json string (I need this data to connect with my RTC provider) but I can't get the user_info on CallEvent object. The line "userInfo = try JSONSerialization.jsonObject(with: data, options: .mutableContainers) as? [String:String]" returns nil.

Can you help me?

Thank you!

**Comment by TatankaConCube** [comment]
do you have any issues in logs in the flutter console?

**Comment by GrupoDO** [comment]
Hello. No, no issues in the console. Just a "nil" in the print of the "userInfo" variable. So, I try to send my userInfo from the push server like this:

{"user_info": "my_data_in_base64url_encoded"} and it works, but....

when the swift part sends the code to the flutter scope, the content of user_info is an _Uint8ArrayView and I cant use it. So I'm editing the lib/src/connectycube_flutter_call_kit.dart file at lines 252 and 258 to add this:

arguments['user_info'] = utf8.decode(arguments['user_info']);
var callEvent = CallEvent.fromMap(arguments);

and add the 'dart:convert' package at the import area.

I can to send a PR with this fix if you want. Please, let me know.

Thank you.

**Comment by TatankaConCube** [comment]
> _Uint8ArrayView

it is [known issue ](https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/39), I'm currently working on it

**Comment by TatankaConCube** [comment]
>arguments['user_info'] = utf8.decode(arguments['user_info']);
var callEvent = CallEvent.fromMap(arguments);
>
> and add the 'dart:convert' package at the import area.
>
> I can to send a PR with this fix if you want. Please, let me know.

but pay attention, it should be compatible with the Android side too

**Comment by TatankaConCube** [comment]
@GrupoDO  the version 2.0.2 was released, try it

**Comment by GrupoDO** [comment]
It works! Thank you!
