### ISSUE TITLE
Callkit not lauching app when screen is locked

### ISSUE THREAD

**Issue by GrupoDO** [ConnectyCube/connectycube-flutter-call-kit#43]
Hello!

I have an issue with the plugin. When the screen is locked and the phone receives a VoIP notification, the CallKit UI is showing but the app is not lauching. So, the UI starts the time counter but not call connected, because I need the app running in order to connect with the RTC server.

If I try the same scenary with WhatsApp it works. The WtahsApp UI is not visible but the status bar change its color to yellow and I think the app is running in background or something. Can I achieve this with the plugin?

Plus when the CallKit launchs from background and I start my app manually with the CallKit UI icon the audio is not working. Can you check this, please?

Thank you so much!

**Comment by TatankaConCube** [comment]
The Call Kit should run your app in the background, please check when you start the connection to your RTC server, maybe you should do it earlier.

> Plus when the CallKit launchs from background and I start my app manually with the CallKit UI icon the audio is not working. Can you check this, please?

do you notify the CallKit about starting the call from the app side?

**Comment by GrupoDO** [comment]
> The Call Kit should run your app in the background, please check when you start the connection to your RTC server, maybe you should do it earlier.
> 
I'm connecting with the RTC server on the callAccepted callback. It is ok? May be I will try to connect before? But I don't know how achieve this, because, before the callback I don't have access to the Flutter scope.


> > Plus when the CallKit launchs from background and I start my app manually with the CallKit UI icon the audio is not working. Can you check this, please?
> 
> do you notify the CallKit about starting the call from the app side?
How can I do that? Is there a method in the plugin to do that?

Thank you for your help :)

**Comment by TatankaConCube** [comment]
> I'm connecting with the RTC server on the callAccepted callback

as I understand, the app starts immediately after first showing the Incoming Call Screen, since this moment you can run the connecting to your RTC server, but I can mistake, check it on your app.

> How can I do that?

try to call the method [`reportCallAccepted`](https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/lib/src/connectycube_flutter_call_kit.dart#L161) after accepting the call on the app side. If the issue won't be solved, we should investigate this case deeply. Please notify us when you found the solution.

**Comment by GrupoDO** [comment]
Hello! I'm trying everything. Now the callKit launches the app from bg, but I can't hear the other participant. I must to mute and unmute my iPhone and then I can hear the other participant. Before I mute the call I get this error in the console:
Error: code: 1701737535, desription: No se pudo completar la operación. (Error de OSStatus 1701737535), Reason


When I use the reportCallAccepted, I get this error in the console:
Domain=com.apple.CallKit.error.requesttransaction Code=5

**Comment by GrupoDO** [comment]
Hello! I add this lines before the provider.reportNewIncomingCall method:

do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playAndRecord, mode: AVAudioSession.Mode.voiceChat)
            try AVAudioSession.sharedInstance().setActive(true)
          } catch {
          }


And I have audio working in foreground, background and terminate state fo the app.
