### ISSUE TITLE
iOS App Not Run update Config Not found

### ISSUE THREAD

**Issue by devalp-pro** [ConnectyCube/connectycube-flutter-call-kit#44]
I m not use ConnectycubeFlutterCallKit.instance.updateConfig(ringtone: 'custom_ringtone', icon: 'app_icon', color: '#07711e');  This method even if when I run the app in in simulator it's give me error below.

[SwiftConnectycubeFlutterCallKitPlugin][handle] method: updateConfig
Could not cast value of type 'NSNull' (0x111ea6f50) to 'NSString' (0x111ea6f38).
2022-02-19 11:04:54.380348+0530 Runner[44844:321335] Could not cast value of type 'NSNull' (0x111ea6f50) to 'NSString' (0x111ea6f38).

**Comment by TatankaConCube** [comment]
[our sample ](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample) works well with this lib

**Comment by sanalkumar1991** [comment]
change ' _let ringtone = arguments["ringtone"] as! String_' and '_let icon = arguments["icon"] as! String_' to ' _let ringtone = arguments["ringtone"] as? String_' and '_let icon = arguments["icon"] as? String_' in ios/.symlinks/plugins/connectycube_flutter_call_kit/ios/Classes/SwiftConnectycubeFlutterCallKitPlugin.swift
