### ISSUE TITLE
[iOS] App icon does not show on CallKit UI

### ISSUE THREAD

**Issue by GrupoDO** [ConnectyCube/connectycube-flutter-call-kit#45]
The app icon is not showing on the app button in the CallKit UI.

AppIcon:
![AppIconCallKit-40](https://user-images.githubusercontent.com/53410779/154803301-8057c466-688a-4666-9bae-af1cfef31b7d.png)

Screenshot:
![IMG_0105](https://user-images.githubusercontent.com/53410779/154803313-c999eeba-c543-4942-b75b-49fd767ad268.jpg)

This is the code that I'm using:

```
ConnectycubeFlutterCallKit.instance.init(
				onCallAccepted: _onCallAccepted,
				onCallRejected: _onCallRejected,
				ringtone: '',
				icon: 'AppIconCallKit',
				color: ''
			);

ConnectycubeFlutterCallKit.instance.updateConfig(ringtone: '', icon: 'AppIconCallKit', color: '');
```

The Console.app shows this line:

`Registering configuration <CXProviderConfiguration 0x2829e8540 localizedName=(null) ringtoneSoundURL=(null) iconTemplateImageData=0x0 maximumCallGroups=1 maximumCallsPerCallGroup=1 supportsAudioOnly=1 supportsVideo=1 supportsEmergency=0 supportsVoicemail=0 supportsCurrentPlatform=1 includesCallsInRecents=0 audioSessionID=144725 supportedHandleTypes=1>`

Thank you.

**Comment by TatankaConCube** [comment]
in [our sample](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/call_kit_manager.dart#L31), it works correctly. Are you sure that you added sources to the project in the correct way and you use the correct name of your sources? One more note - if you don't want to specify `ringtone` or `color` just skip it or set `null`.

**Comment by GrupoDO** [comment]
Hello! I've tried everything. The only thong that works was add this lines at providerConfiguration: CXProviderConfiguration

```
let iconMaskImage = #imageLiteral(resourceName: "IconMask")
providerConfiguration.iconTemplateImageData = iconMaskImage.pngData()

```


And if I not specify an empty string for ringtone or color I get an error from Swift that those strings can not be null.
