### ISSUE TITLE
How to remove this Japanese Text from calling UI?

### ISSUE THREAD

**Issue by Usamamajid13** [ConnectyCube/connectycube-flutter-call-kit#49]
I'm calling from another app and showing this UI on lock screen but there is a Japanese Text written on the calling UI which translates into "Video calling phone". How can I remove this thing from the UI? There is nothing written like this in the package
![WhatsApp Image 2022-04-05 at 11 38 29 AM](https://user-images.githubusercontent.com/83748784/161694249-48192421-4302-40f3-9776-08c455dba6b8.jpeg)
.

**Comment by TatankaConCube** [comment]
hmm... we haven't added any translations yet in this plugin. Can it be some system feature in your ROM for translation text on the screen?

**Comment by Usamamajid13** [comment]
I have checked it on multiple devices and emulators including Samsung a50, Google Pixel 4. Can you help me remove this if you have any solution please let me know! thank you!

**Comment by TatankaConCube** [comment]
As we can see on the screenshot, you use the modified plugin (custom background, avatar) and we don't know which other modifications are presented there.

**Comment by Usamamajid13** [comment]
I just assigned the image and name to the package variable and it is displaying the image along with the name. I haven't touched anything else. So If you find a solution please let me know. Can it be the native thing that android is showing automatically?

**Comment by Usamamajid13** [comment]
Hello, Do you get any information on this?
