### ISSUE TITLE
Android accept call not working and getCallData getting null

### ISSUE THREAD

**Issue by Chinmaybixie** [ConnectyCube/connectycube-flutter-call-kit#53]
I have got the same problem when I accept calls in terminate mode, I have to call the getCallData. but I didn't get any data in response. And check with getCallState but it will get the unknown response.

**Comment by TatankaConCube** [comment]
we made some fixes in the new version [2.0.3](https://pub.dev/packages/connectycube_flutter_call_kit/versions/2.0.3), please try it

**Comment by Chinmaybixie** [comment]
Still getting same issue
