### ISSUE TITLE
 SYSTEM_ALERT_WINDOW permission when my app on background didn't receive permission request on android 12

### ISSUE THREAD

**Issue by AmirhosseinShk** [ConnectyCube/connectycube-flutter-call-kit#55]
@TatankaConCube I have problem related to [this ](https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/51)issue and its about get SYSTEM_ALERT_WINDOW permission when my app on background and didn't receive permission request and get error :
Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, Unable to detect current Android Activity., null)

are u have any idea for this problem can be helpful? please share with me.

**Comment by TatankaConCube** [comment]
@AmirhosseinShk  we implemented the required functionality in our [P2P calls sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample), you can review it, it may contain the solution for your issue. Or you can revise [this commit](https://github.com/ConnectyCube/connectycube-flutter-samples/commit/ee3610ecbec49cbdd30a2920ad3f61294e658865) with the implementation of this feature.
