### ISSUE TITLE
callNotification showing in debug but not showing in release

### ISSUE THREAD

**Issue by Basemshawwa** [ConnectyCube/connectycube-flutter-call-kit#72]
callNotification showing in debug but not showing in release, any solution please ?
![Screen Shot 2022-10-12 at 2 59 04](https://user-images.githubusercontent.com/45998555/195313276-fe43a794-bc75-491f-8e83-0e9a2fce0e3f.png)

**Comment by TatankaConCube** [comment]
which platform do you mean?

**Comment by Basemshawwa** [comment]
Android

**Comment by Basemshawwa** [comment]
> which platform do you mean?

android

**Comment by AbdArahman2001** [comment]
@Basemshawwa 
hi bro, I'm facing the same problem, did you find a solution?

**Comment by maulikchak** [comment]
@pragma('vm:entry-point')

add this line before you call the background handler out side void main

**Comment by JulianBissekkou** [comment]
I guess this should be documented.
