### ISSUE TITLE
video call notification dismissed when click on notification

### ISSUE THREAD

**Issue by santhoshrao519** [ConnectyCube/connectycube-flutter-call-kit#74]
When i touch incoming video call notification, its get disappeared. How to fix this? Please help

**Comment by booooohdan** [comment]
Still an actual for Android. I think notification must disappear only if the "Accept" or "Reject" button was clicked

**Comment by TatankaConCube** [comment]
It doesn't make sense to open the notification one more time, on my opinion the app should be started and the Incoming call sheet or bubble or something else should be shown inside the app.
