### ISSUE TITLE
Notification ringtone sound not working

### ISSUE THREAD

**Issue by MrunalrajRedij** [ConnectyCube/connectycube-flutter-call-kit#77]
**Platform:**
Android

**Describe the bug:**
The notifications sound is not working for p2p calls.

**Additional info:**
I am getting incoming call notifications, but the ringtone is not working on both call notifications and full-screen notifications (when the device is in sleep mode). 

**Tested on:**
Emulator: From android 9 to 12
Physical devices: From android 9 to 12

**Comment by TatankaConCube** [comment]
Could you review the log of your app and search the log with the tag `NotificationsManager`? There will be printed lines with the selected ringtone. Check if it is present by the displayed path.

**Comment by MrunalrajRedij** [comment]
**This are the notification logs when notification appears:**
2022-12-01 15:58:57.308 5624-5624/com.mobile.spiconn.dev D/NotificationsManager: customRingtone custom_ringtone
2022-12-01 15:58:57.308 5624-5624/com.mobile.spiconn.dev D/NotificationsManager: ringtone 1 android.resource://com.mobile.spiconn.dev/raw/custom_ringtone
2022-12-01 15:58:57.308 5624-5624/com.mobile.spiconn.dev D/NotificationsManager: ringtone 2 android.resource://com.mobile.spiconn.dev/raw/custom_ringtone

**Comment by TatankaConCube** [comment]
do you have the resource with the name `custom_ringtone` in the **res** directory of your Android project by path `app_name/android/app/src/main/res/raw/custom_ringtone.mp3`?

**Comment by MrunalrajRedij** [comment]
No, I dont have the mp3 file on specified path. I thought package is taking default ringtone of device. Also, I remember at first the ringtone was working fine and I haven't place any mp3 file in res.

**Comment by TatankaConCube** [comment]
then delete the parameter `ringtone` from the [initialization method](https://github.com/ConnectyCube/connectycube-flutter-call-kit#listen-in-the-foreground) or set `null` or empty string there

**Comment by MrunalrajRedij** [comment]
Okay, It seems to be working. And thanks for the additional comment, It made it easy for me to test. Otherwise, I may have spent a lot of time trying without uninstalling the app. 
Before you close this issue, I want to test it on different devices to ensure it works on all versions. Please wait for then. I will comment on this issue as soon as the tests are done. Thanks

**Comment by TatankaConCube** [comment]
Close the ticket by yourself if the issue was resolved.

**Comment by MrunalrajRedij** [comment]
I tested this on different devices, and it's working correctly. Will close the issue now. Thanks.
