### ISSUE TITLE
Not working in terminated state

### ISSUE THREAD

**Issue by nguyenxuankiet262** [ConnectyCube/connectycube-flutter-call-kit#79]
ConnectycubeFlutterCallKit.onCallAcceptedWhenTerminated = onCallAcceptedWhenTerminated;

 ConnectycubeFlutterCallKit.onCallRejectedWhenTerminated = onCallRejectedWhenTerminated;

ConnectycubeFlutterCallKit.initEventsHandler();

onCallAcceptedWhenTerminated and onCallRejectedWhenTerminated functions are top-level function

i put above code inside firebaseMessagingBackgroundHandler but when i clicked reject and accept button of incoming call, there were no callbacks.
These are some logs from logcat when i clicked reject button
I see this error: MissingPluginException(No implementation found for method `startBackgroundIsolate` on channel connectycube_flutter_call_kit.methodChannel)
2022-12-08 17:21:46.092 2792-2792/? E/FlutterConnectycubeBackgroundExecutor: Background isolate already started.
2022-12-08 17:21:46.094 2792-2825/? I/ConnectycubeFlutterBgPerformingService: Service has not yet started, messages will be queued.

**Comment by benyaminbeyzaie** [comment]
Same issue

**Comment by benyaminbeyzaie** [comment]
I've tried this but can't solve the issue https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/72

**Comment by TatankaConCube** [comment]
Mark your callbacks with the `@pragma('vm:entry-point')` annotation and use the latest version of the plugin
