### ISSUE TITLE
On callaccept - Run flutter on specific screen

### ISSUE THREAD

**Issue by Mr-Slimon** [ConnectyCube/connectycube-flutter-call-kit#8]
Is it possible to run Flutter on specific screen instead of running the application from start ?

I found the code that launch the application in `ConnectycubeFlutterCallKitPlugin.kt`

Is there a way to modify it so it launch flutter on specific screen and pass the parameters to that screen ?

```
ACTION_CALL_ACCEPT -> {
                saveCallState(callIdToProcess!!, CALL_STATE_ACCEPTED)

                channel.invokeMethod("onCallAccepted", parameters)

                val launchIntent = getLaunchIntent(context!!)
                launchIntent?.action = ACTION_CALL_ACCEPT
                context.startActivity(launchIntent)
                }
```

**Comment by TatankaConCube** [comment]
@Mr-Slimon unfortunately we don't support this functionality in the current realization.
