### ISSUE TITLE
Terminate State

### ISSUE THREAD

**Issue by Gagandeep1408** [ConnectyCube/connectycube-flutter-call-kit#83]
If app is terminate and removed from back stack then it will work or not?

**Comment by TatankaConCube** [comment]
Do you mean Android and iOS? If so - yes it will work using the Push notifications feature, it is the main reason for using this plugin.

**Comment by Gagandeep1408** [comment]
ok you mean if android and iOS app clear from back stack and push notification came then calling Widget will visible.

**Comment by TatankaConCube** [comment]
yes, you can see how it works in our [P2P Calls sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample)

**Comment by Gagandeep1408** [comment]
Sure Thank you for quick response
