### ISSUE TITLE
Multiple callback of "onCallAccepted" and "onCallRejected". Issue is for iOS only

### ISSUE THREAD

**Issue by booooohdan** [ConnectyCube/connectycube-flutter-call-kit#87]
In initState I initialized the plugin:
```
WidgetsBinding.instance.addPostFrameCallback(
      (_) async {
      ConnectycubeFlutterCallKit.instance.init(
          icon: 'facility_logo',
          color: '#653CBC',
          onCallAccepted: _onCallAccepted,
          onCallRejected: _onCallRejected,
        );
}
```

for iOS `_onCallAccepted` and `_onCallRejected` calls multiple times. For Android, all are working fine and call only once

**Comment by booooohdan** [comment]
Look, three "Accept" callbacks and two "Reject" in less than a second duration when I tap "Answer". It's always a random count of callbacks
![image](https://user-images.githubusercontent.com/30977443/219719354-6919e108-c9b4-4518-b685-6a60743cf51d.png)

For rejecting, the callback is also duplicated
![image](https://user-images.githubusercontent.com/30977443/219720069-3486e2f3-8e1a-4a6f-afa6-7efc1181abdc.png)

**Comment by TatankaConCube** [comment]
You can try to investigate it on your side and share the result here and I will try to apply your fixes the next week.
