### ISSUE TITLE
Method "getCallData" return wrong type of "userInfo" parameter

### ISSUE THREAD

**Issue by booooohdan** [ConnectyCube/connectycube-flutter-call-kit#88]
In my `backgroundHandler` I create `CallEvent` object and pass it `showCallNotification` method
```
final callEvent = CallEvent(
      sessionId: uuid,
      callType: callType,
      callerId: callId,
      callerName: callerName,
      opponentsIds: const {0},
      userInfo: {'docId': docId},
    );
await ConnectycubeFlutterCallKit.showCallNotification(callEvent);
```

But the object from `getCallData` is a **String**, not a **map item**:
<img width="288" alt="Знімок екрана 2023-02-17 о 19 21 02" src="https://user-images.githubusercontent.com/30977443/219723173-be845058-0165-4cc9-8ae7-07788a36bf2a.png">

**Comment by TatankaConCube** [comment]
In the `userInfo` field we expect the map with the `String` key and with the `String` value. You can try to encode to string and decode from string the map on your side by yourself.

**Comment by waqarali27324** [comment]
@TatankaConCube I'm also getting this Null value
