### ISSUE TITLE
Why is systemAlertWindow permission necessary ? (Draw over other apps permission)

### ISSUE THREAD

**Issue by MrunalrajRedij** [ConnectyCube/connectycube-flutter-call-kit#93]
If I do not ask for **systemAlertWindow permission (Draw over other apps/Appear on top permission)** or user do not accept that permission. 
The app will show call notification but clicking upon it, app will not start the app (in case terminated) or app will not come to foreground.
Why is that? and why is it necessary to give such permission. 
Apps like WhatsApp, Signal etc. don't have this permission, yet these apps tends to start/come to foreground when clicked on call notifications.
And also this is not a simple _Alloy and Deny_ permission user has to go in particular setting and then click on _enable_. Is there any way I can bypass this permission while not impacting functionality?

**Comment by TatankaConCube** [comment]
I'm not sure that WhatsApp or Signal uses Flutter inside))) There are a few ways for launching the app from the notification and we have chosen the simplest one for our plugin (by requesting this permission).  If you have other solutions you can share them here.

**Comment by MrunalrajRedij** [comment]
Thanks for your reply. 
If anyone stumbles upon this issue thread. Please comment, on alternative solutions for launching the app. As giving this permission seems little intrusive.
