### ISSUE TITLE
Connectycube - flutter | what inside accept call method while the app is terminated is not readble

### ISSUE THREAD

**Issue by alito0697** [ConnectyCube/connectycube-flutter-call-kit#95]
`Future onCallAcceptedWhenTerminated(CallEvent callEvent) async {
_joinMeetingVideo();
}
ConnectycubeFlutterCallKit.onCallAcceptedWhenTerminated = onCallAcceptedWhenTerminated;
`
The `_joinMeetingVideo()` is not readble it's like `onCallAcceptedWhenTerminated` is empty

**Comment by alito0697** [comment]
@TatankaConCube if you know how to solve the issue please answer but if not don't close the discussion because it's a different topic

**Comment by TatankaConCube** [comment]
We made this plugin open source, all code is completely available for every developer. You have an unusual case for your needs and you can investigate your issue by yourself. If the issue is related to the plugin's main logic you can share the solution by making the pull request.
