### ISSUE TITLE
CallEvent does accept callerId as dart int but later casts to Java Int

### ISSUE THREAD

**Issue by DooMMasteR** [ConnectyCube/connectycube-flutter-call-kit#97]
Dart integers are 64 bit and easily exceeds the range of a Java Int. Should callerId ever be larger than a Java int the operation will Except.

**Comment by DooMMasteR** [comment]
I guess any Dart `int` should rather be a Java `long` not `int`

**Comment by TatankaConCube** [comment]
you are right, it makes sense while using this plugin in infrastructure different from the Connectycube but for the Connectycube we are sure that the user id can't be more than the max integer value.
